### ISSUE TITLE
Parity with node?

### ISSUE THREAD

**Issue by ronag** [mafintosh/end-of-stream#25]
Node contains some improvements to this utility which might be useful for users that use this package over the node version.

Should we try to use the node version if available and otherwise fallback to this?

```js
module.exports = stream.finished || eos;
```

or should we keep this module updated with the actual code from node?

or maybe at least put a note in the README linking to the information in node?

@mafintosh

**Comment by mafintosh** [comment]
Depending on the changes to the Node version I prefer to keep this up to date (for example by including your recent return-immediately-if-already-destroyed), but I'd prefer not to include a verbatim copy of the Node.js one.

All-in-all this is super stable as is, and should not require many changes.

**Comment by ronag** [comment]
Fair enough.

I'd also recommend including listening to `'aborted'`.
