### ISSUE TITLE
Test fails with node >= 10.16

### ISSUE THREAD

**Issue by guimard** [mafintosh/end-of-stream#26]
Hi,

I had to modify test to pass with node >= 10.16 :
```diff
--- a/test.js
+++ b/test.js
@@ -9,7 +9,7 @@
 var ws = fs.createWriteStream('/dev/null');
 eos(ws, function(err) {
        expected--;
-       assert(!!err);
+       assert(!err);
        assert(this === ws);
        if (!expected) process.exit(0);
 });
```

**Comment by guimard** [comment]
Also `expected` is not decreased to 0: last test (listen) is never called

**Comment by Hexxeh** [comment]
Also seeing this affect @fitbit/sdk, builds are no longer competing. Reverting to 1.4.1 works, so it seems like there was some breaking change here.

**Comment by mafintosh** [comment]
@Hexxeh 1.4.2 fails for you but 1.4.1 works?

**Comment by Hexxeh** [comment]
Yeah. With 1.4.2, the stream never finishes and we get no emitted file. If I revert to 1.4.1 by specifying it via resolutions, it works as before. Specifically it's the changes in index.js at https://github.com/mafintosh/end-of-stream/commit/25b242518f50571c3348cff11553712cbf832d04 that triggered this.

**Comment by mafintosh** [comment]
@Hexxeh can you share code/gist/test where that fails? If anything that could make it call the eos cb earlier rather than later/never

**Comment by mafintosh** [comment]
(closing this issue as this test is fixed in master, still interested in the bug above tho)

**Comment by mafintosh** [comment]
Can you share where eos hangs in that script?

**Comment by Hexxeh** [comment]
It doesn't hang, the process ends presumably because no further events are queued. We use a lot of streams throughout the build process so I'm still trying to track down why exactly that change causes us a problem.

**Comment by Hexxeh** [comment]
Seems to be an interaction with multistream (https://github.com/feross/multistream). That module serializes an array of readable streams. Once they're all done, it destroys itself.

It seems end-of-stream now considers that to be a premature close, but it isn't intentionally.

**Comment by mafintosh** [comment]
Perfect, I’ll look into that tmw

**Comment by guimard** [comment]
Thanks, uplodaded to [Debian unstable](https://www.debian.org/)

**Comment by Hexxeh** [comment]
Any chance we can revert this change until we understand where the problem lies?

**Comment by mafintosh** [comment]
@Hexxeh I just released 1.4.4 that should fix it. If not let me know.

**Comment by Hexxeh** [comment]
Yeah, that fixed it! Awesome, thank you! :)

**Comment by mafintosh** [comment]
https://twitter.com/mafintosh/status/1176845777580285952
