### ISSUE TITLE
Legacy duplex stream does not end

### ISSUE THREAD

**Issue by rasenplanscher** [mafintosh/end-of-stream#5]
I'm switching to gulp 4 and I've run into an issue that I could trace to end-of-stream. I use [stream-combiner](https://github.com/dominictarr/stream-combiner) to build a few of my streams, and those are recognized as legacy streams. Now, being duplex streams, those do not get closed properly, which makes gulp think they haven't been closed at all.

After looking through all the involved packages, I think, there's an error [here](https://github.com/mafintosh/end-of-stream/blob/master/index.js#L24-L26):
```
var onlegacyfinish = function() {
	if (!stream.writable) onfinish();
};
```

Is the exclamation mark meant to be there? To me, that doesn't doesn't seem right... Could you enlighten me?

**Comment by mafintosh** [comment]
stream-combiner produces a legacy stream and legacy streams should have `.writable = true` if they are writable. if you look through the stream-combiner code you'll see that the `.writable` property is set by https://github.com/Raynos/duplexer/blob/master/index.js#L38-L39 (aka the first stream in your pipeline) so maybe that stream isn't setting `.writable` correctly?

my suggestion would be to use a streams2 version of stream-combiner (fx https://github.com/mafintosh/pumpify) to avoid having to deal with the legacy state machine at all

**Comment by rasenplanscher** [comment]
Thanks a bunch! Switched to your pumpify and everything's a-ok :D
